export declare const uriAttrs: string[];
export declare const ARIA_ATTRIBUTE_PATTERN: RegExp;
export declare const DefaultWhitelist: {
    '*': (string | RegExp)[];
    a: string[];
    area: any[];
    b: any[];
    br: any[];
    col: any[];
    code: any[];
    div: any[];
    em: any[];
    hr: any[];
    h1: any[];
    h2: any[];
    h3: any[];
    h4: any[];
    h5: any[];
    h6: any[];
    i: any[];
    img: string[];
    li: any[];
    ol: any[];
    p: any[];
    pre: any[];
    s: any[];
    small: any[];
    span: any[];
    sub: any[];
    sup: any[];
    strong: any[];
    u: any[];
    ul: any[];
};
/**
 * A pattern that recognizes a commonly useful subset of URLs that are safe.
 *
 * Shoutout to Angular 7 https://github.com/angular/angular/blob/7.2.4/packages/core/src/sanitization/url_sanitizer.ts
 */
export declare const SAFE_URL_PATTERN: RegExp;
/**
 * A pattern that matches safe data URLs. Only matches image, video and audio types.
 *
 * Shoutout to Angular 7 https://github.com/angular/angular/blob/7.2.4/packages/core/src/sanitization/url_sanitizer.ts
 */
export declare const DATA_URL_PATTERN: RegExp;
export declare const ParseableAttributes: string[];
/** Used to compose unicode character classes. */
export declare const rsComboMarksRange = "\\u0300-\\u036f", reComboHalfMarksRange = "\\ufe20-\\ufe2f", rsComboSymbolsRange = "\\u20d0-\\u20ff", rsComboMarksExtendedRange = "\\u1ab0-\\u1aff", rsComboMarksSupplementRange = "\\u1dc0-\\u1dff", rsComboRange: string;
/** Used to compose unicode capture groups. */
export declare const rsCombo: string;
/**
 * Used to match [combining diacritical marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) and
 * [combining diacritical marks for symbols](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks_for_Symbols).
 */
export declare const reComboMark: RegExp;
export declare const escapeMap: {
    '&': string;
    '<': string;
    '>': string;
    '"': string;
    "'": string;
    '`': string;
};
/** Used to map Latin Unicode letters to basic Latin letters. */
export declare const deburredLetters: {
    À: string;
    Á: string;
    Â: string;
    Ã: string;
    Ä: string;
    Å: string;
    à: string;
    á: string;
    â: string;
    ã: string;
    ä: string;
    å: string;
    Ç: string;
    ç: string;
    Ð: string;
    ð: string;
    È: string;
    É: string;
    Ê: string;
    Ë: string;
    è: string;
    é: string;
    ê: string;
    ë: string;
    Ì: string;
    Í: string;
    Î: string;
    Ï: string;
    ì: string;
    í: string;
    î: string;
    ï: string;
    Ñ: string;
    ñ: string;
    Ò: string;
    Ó: string;
    Ô: string;
    Õ: string;
    Ö: string;
    Ø: string;
    ò: string;
    ó: string;
    ô: string;
    õ: string;
    ö: string;
    ø: string;
    Ù: string;
    Ú: string;
    Û: string;
    Ü: string;
    ù: string;
    ú: string;
    û: string;
    ü: string;
    Ý: string;
    ý: string;
    ÿ: string;
    Æ: string;
    æ: string;
    Þ: string;
    þ: string;
    ß: string;
    Ā: string;
    Ă: string;
    Ą: string;
    ā: string;
    ă: string;
    ą: string;
    Ć: string;
    Ĉ: string;
    Ċ: string;
    Č: string;
    ć: string;
    ĉ: string;
    ċ: string;
    č: string;
    Ď: string;
    Đ: string;
    ď: string;
    đ: string;
    Ē: string;
    Ĕ: string;
    Ė: string;
    Ę: string;
    Ě: string;
    ē: string;
    ĕ: string;
    ė: string;
    ę: string;
    ě: string;
    Ĝ: string;
    Ğ: string;
    Ġ: string;
    Ģ: string;
    ĝ: string;
    ğ: string;
    ġ: string;
    ģ: string;
    Ĥ: string;
    Ħ: string;
    ĥ: string;
    ħ: string;
    Ĩ: string;
    Ī: string;
    Ĭ: string;
    Į: string;
    İ: string;
    ĩ: string;
    ī: string;
    ĭ: string;
    į: string;
    ı: string;
    Ĵ: string;
    ĵ: string;
    Ķ: string;
    ķ: string;
    ĸ: string;
    Ĺ: string;
    Ļ: string;
    Ľ: string;
    Ŀ: string;
    Ł: string;
    ĺ: string;
    ļ: string;
    ľ: string;
    ŀ: string;
    ł: string;
    Ń: string;
    Ņ: string;
    Ň: string;
    Ŋ: string;
    ń: string;
    ņ: string;
    ň: string;
    ŋ: string;
    Ō: string;
    Ŏ: string;
    Ő: string;
    ō: string;
    ŏ: string;
    ő: string;
    Ŕ: string;
    Ŗ: string;
    Ř: string;
    ŕ: string;
    ŗ: string;
    ř: string;
    Ś: string;
    Ŝ: string;
    Ş: string;
    Š: string;
    ś: string;
    ŝ: string;
    ş: string;
    š: string;
    Ţ: string;
    Ť: string;
    Ŧ: string;
    ţ: string;
    ť: string;
    ŧ: string;
    Ũ: string;
    Ū: string;
    Ŭ: string;
    Ů: string;
    Ű: string;
    Ų: string;
    ũ: string;
    ū: string;
    ŭ: string;
    ů: string;
    ű: string;
    ų: string;
    Ŵ: string;
    ŵ: string;
    Ŷ: string;
    ŷ: string;
    Ÿ: string;
    Ź: string;
    Ż: string;
    Ž: string;
    ź: string;
    ż: string;
    ž: string;
    Ĳ: string;
    ĳ: string;
    Œ: string;
    œ: string;
    ŉ: string;
    ſ: string;
};
/** Used to match Latin Unicode letters (excluding mathematical operators). */
export declare const reLatin: RegExp;
export declare const keyCodeMap: {
    32: string;
    48: string;
    49: string;
    50: string;
    51: string;
    52: string;
    53: string;
    54: string;
    55: string;
    56: string;
    57: string;
    59: string;
    65: string;
    66: string;
    67: string;
    68: string;
    69: string;
    70: string;
    71: string;
    72: string;
    73: string;
    74: string;
    75: string;
    76: string;
    77: string;
    78: string;
    79: string;
    80: string;
    81: string;
    82: string;
    83: string;
    84: string;
    85: string;
    86: string;
    87: string;
    88: string;
    89: string;
    90: string;
    96: string;
    97: string;
    98: string;
    99: string;
    100: string;
    101: string;
    102: string;
    103: string;
    104: string;
    105: string;
};
export declare const keyCodes: {
    ESCAPE: number;
    ENTER: number;
    SPACE: number;
    TAB: number;
    ARROW_UP: number;
    ARROW_DOWN: number;
};
export declare const EVENT_KEY = ".bs.select";
export declare const classNames: {
    DISABLED: string;
    DIVIDER: string;
    SHOW: string;
    DROPUP: string;
    MENU: string;
    MENURIGHT: string;
    MENULEFT: string;
    BUTTONCLASS: string;
    POPOVERHEADER: string;
    ICONBASE: string;
    TICKICON: string;
};
export declare const Selector: {
    MENU: string;
    DATA_TOGGLE: string;
};
export declare const elementTemplates: {
    div: HTMLDivElement;
    span: HTMLSpanElement;
    text: HTMLSpanElement;
    checkMark: HTMLSpanElement;
    i: HTMLElement;
    subtext: HTMLElement;
    a: HTMLAnchorElement;
    li: HTMLLIElement;
    noResults: HTMLLIElement;
    whitespace: Text;
    fragment: DocumentFragment;
    option: HTMLOptionElement;
    selectedOption: HTMLOptionElement;
};
