export interface BootstrapSelectOptions {
    noneSelectedText: string;
    noneResultsText: string;
    countSelectedText(numSelected: number, _numTotal: number): "{0} item selected" | "{0} items selected";
    maxOptionsText(numAll: number, numGroup: number): string[];
    local: string;
    selectAllText: string;
    deselectAllText: string;
    doneButton: boolean;
    multipleSeparator: string;
    style: string;
    size: string;
    title: any;
    placeholder: any;
    allowClear: boolean;
    selectedTextFormat: string;
    width: string;
    header: boolean | string;
    search: boolean;
    searchPlaceholder: any;
    normalizeSearch: boolean;
    actionsBox: boolean;
    tickIcon: string;
    showTick: boolean;
    template: {
        dropdownButton: ($el: HTMLSelectElement) => string;
        dropdown: () => string;
        dropdownMenu: () => string;
        serchInput: () => string;
        header: () => string;
        item: ($el: HTMLOptionElement) => string;
        optgroup: ($el: HTMLOptGroupElement) => string;
        option: ($el: HTMLOptionElement, multiple: boolean) => string;
        divider: () => string;
        checkMark: () => string;
    };
    maxOptions: boolean;
    mobile: boolean;
    selectOnTab: boolean;
    dropdownPosition: string;
    virtualScroll: number;
};
