export declare type SelectpickerOptions = {
    noneSelectedText: string;
    noneResultsText: string;
    countSelectedText(numSelected: number, _numTotal: number): "{0} item selected" | "{0} items selected";
    maxOptionsText(numAll: number, numGroup: number): string[];
    selectAllText: string;
    deselectAllText: string;
    source: {
        pageSize: number;
    };
    chunkSize: number;
    doneButton: boolean;
    doneButtonText: string;
    multipleSeparator: string;
    styleBase: string;
    style: string;
    size: string;
    title: any;
    placeholder: any;
    allowClear: boolean;
    selectedTextFormat: string;
    width: boolean;
    container: boolean | HTMLElement;
    hideDisabled: boolean;
    showSubtext: boolean;
    showIcon: boolean;
    showContent: boolean;
    dropupAuto: boolean;
    header: boolean;
    liveSearch: boolean;
    liveSearchPlaceholder: any;
    liveSearchNormalize: boolean;
    liveSearchStyle: string;
    actionsBox: boolean;
    iconBase: string;
    tickIcon: string;
    showTick: boolean;
    template: {
        caret: string;
    };
    maxOptions: boolean;
    mobile: boolean;
    selectOnTab: boolean;
    dropdownAlignRight: boolean;
    windowPadding: number | number[];
    virtualScroll: number;
    display: boolean | 'static';
    sanitize: boolean;
    sanitizeFn: any;
    whiteList: {
        '*': (string | RegExp)[];
        a: string[];
        area: any[];
        b: any[];
        br: any[];
        col: any[];
        code: any[];
        div: any[];
        em: any[];
        hr: any[];
        h1: any[];
        h2: any[];
        h3: any[];
        h4: any[];
        h5: any[];
        h6: any[];
        i: any[];
        img: string[];
        li: any[];
        ol: any[];
        p: any[];
        pre: any[];
        s: any[];
        small: any[];
        span: any[];
        sub: any[];
        sup: any[];
        strong: any[];
        u: any[];
        ul: any[];
    };
};
